---
title: "Day 3 activities"
author: "Felicia Cruz"
date: "8/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


### Part 1: Conditional Statements and For Loops
```{r}
pm2_5 <- 160

if (pm2_5 < 100){
  print("Low to moderate risk")
} else if (pm2_5>= 100 & pm2_5<150){
  print("Unhealthy for sensitive groups")
} else if(pm2_5 >= 150){
  print("Health risk present")
}

```

```{r}
species <- "blue whale"
if (str_detect(species, pattern = "whale")) {
  print("You found a whale!")
}

```

```{r}
max_airtemp_c <- 24.1 

if (max_airtemp_c > 27){
  print("Temperature too high")
} else{
  print("Temperature OK")
}
```

```{r}
base_burrito <- 6.50
main_ingredient <- "steak"

if(main_ingredient == "veggie"){
  print(base_burrito)
} else if (main_ingredient == "chicken") {
  print(base_burrito + 3)
} else if (main_ingredient == "steak"){
  print(base_burrito + 3.25)
}

```

### For loops 

```{r}
fish <- c(8, 10, 12, 23)

for (i in seq_along(fish)){
  print(fish[i] / sum(fish))
}
```

```{r}
for (i in seq_along(month.name)){
  print(paste(month.name[i], "is month", i))
}

```

